version: "3.8"
services:
  nginx:
    image: nginx:1.21.6
    container_name: nginx
    ports:
      - "3001:3001"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: web
    volumes:
      - ./src:/src
    expose:
      - "3001"
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1234
      - DATABASE_HOST=localhost
  db:
    image: postgres:14.2-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 1234
    expose:
      - "5432"
